### ISSUE TITLE
Can't get the XCode template setup to work

### ISSUE THREAD

**Issue by fastone** [unify/unify#1]
Tried the setup.sh script to install the XCode templates, but it doesn't work. I don't see the template when creating a new XCode project.

**Comment by swernerx** [comment]
Have you tried to restart XCode afterwards. The path should be listed in the settings under "source trees" afterwards. Please check this.

**Comment by fastone** [comment]
After modifying the setup.sh file, it worked for me.

**Comment by swernerx** [comment]
What was your modification? Maybe helpful to share it, so other users can benefit from it. Thanks.

**Comment by fastone** [comment]
I just hardcoded my paths in the setup.sh file, a bit nasty and ugly.
