### ISSUE TITLE
possible initialization exeption in scroll Indicator 

### ISSUE THREAD

**Issue by dominikg** [unify/unify#110]
Sometimes the following exception occurs during application initializaion:

Uncaught qx.core.AssertionError: Expected value to be a DOM element but found  'null'!

it looks like _applyOrientation executes while _hasElement returns true, but __startElem is not jet set.

This is a bit strange because a) it happens only sometimes and i havn't found a way to reproduce it reliably jet
and b) _createElement sets __startElem, so in theory it should be there.

Maybe the IIndicator interface is the culprit?

A possible solution could be to remove the possibility to change orientation property from Indicator altogether and only use a private internal field instead of a qooxdoo property to save its value.

Stacktrace:

qx.Class.define.statics.__failAssert.js:81
qx.Class.define.statics.assertElementAssert.js:819
qx.Class.define.statics.setStylesStyle.js:427
qx.Class.define.members.__setSliderStyleIndicator.js:166
qx.Class.define.members._applyOrientationIndicator.js:330
(anonymous function)
qx.Class.define.constructIndicator.js:89
wrapperClass.js:1623
qx.Class.define.constructScroll.js:44
.....

**Comment by fastner** [comment]
Fixed by pul request #111
