### ISSUE TITLE
support for the placeholder tag on input widgets

### ISSUE THREAD

**Issue by mojoaxel** [unify/unify#113]
unify.ui.form.TextArea and unify.ui.form.TextField should support the [placeholder tag](http://www.whatwg.org/specs/web-apps/current-work/multipage/common-input-element-attributes.html#the-placeholder-attribute) since it is [implemented in current versions of webkit and gecko](http://www.miketaylr.com/code/input-type-attr.html).

**Comment by fastner** [comment]
This is done with blur/focus events in #114 and #115.
