### ISSUE TITLE
Label.setValue() does not resize the widget to the new content

### ISSUE THREAD

**Issue by mojoaxel** [unify/unify#19]
If a _unify.ui.basic.Label_ is created with an empty value string and the value is set afterwards wit _setValue_ the width of the widget is not updated.

``` js
var label = new unify.ui.basic.Label("");
```

Later in time:

``` js
label.setValue("I'm not insane, my mother had me tested!");
```

A workaround that could be used at the moment:

``` js
label.set({
    value: "I'm not insane, my mother had me tested!",
    width: 300 //dirty!
});
```

**Comment by fastner** [comment]
Relayout applies after setting new label value
