### ISSUE TITLE
XCode Template, missing PhoneGap

### ISSUE THREAD

**Issue by ghost** [unify/unify#2]
The installation instructions don't mention where to install PhoneGap when creating a new XCode project from the Unify Project template.
So a new project will fail building with a lot of missing files.

I'd like to see clear installation instructions on where to install base unify, qooxdoo and PhoneGap to start working with unify.

**Comment by fastner** [comment]
You can now find a new tutorial about setting up xcode to work with unify at http://www.unify-training.com/setting-up-xcode.html
If you have more issues after reading that please add it here.

**Comment by fastner** [comment]
It is an issue with the Base SDK setting of phonegap. Should be fixed with the newest version.
