### ISSUE TITLE
unify/ui/layout/special/NavigationBar should calculate the available witdh for the title element

### ISSUE THREAD

**Issue by dominikg** [unify/unify#45]
currently it uses the titles width hint, which can be bigger than whats there.

Its max width should be the space that is available between the left and right elements. 

Bonus: unify pre widget allowed left/title/right areas to be given a percentual width (e.g. 25%/50%/25%). Should the NavigationBar widget offer the same possibilities?

**Comment by fastner** [comment]
From commit message:
- optimal position: title is centered on the navigation bar
- avail centered position: title is smaller than avail space between right and left buttons, but can not be positioned centered on navigation bar. title is cented on the avail space
- title too big: title is cropped to the avail space

This positioning is done automatically.
