### ISSUE TITLE
ZyngaScroller: The "scrollend" event should be fired every time a scroll has been executed

### ISSUE THREAD

**Issue by mojoaxel** [unify/unify#56]
The ZyngaScroller should fire a "scrollend" event every time a scroll has been executed. At the moment, this event is only executed if the scroll process is started manually. The event should also be fired if the scrolling was initiated by calling a function (e.g. scrollTo).

**Comment by fastner** [comment]
Fixed in commit 625f2129f28a2e0973cf05b6dd0c831034d52c0e
