### ISSUE TITLE
unify build does not use all code optimizations offered by qooxdoo

### ISSUE THREAD

**Issue by dominikg** [unify/unify#62]
Qooxdoo offers the following optimizations: ["basecalls", "comments", "privates", "strings", "variables", "variants"]
but unify only uses optimize :  [ "variables", "privates", "basecalls" ]  in application.json line 136
are the other ones unsafe or should the optimize configuration  be updated?

**Comment by fastner** [comment]
You're right, we can use all of them. I added it to the default unify configuration.
