### ISSUE TITLE
cannot call method getId of null when closing popover in ViewOverlayManager

### ISSUE THREAD

**Issue by dominikg** [unify/unify#88]
stacktrace:

Uncaught TypeError: Cannot call method 'getId' of null
qx.Class.define.members.__hidePopover  /unify/framework/source/class/unify/view/helper/ViewOverlayManager.js?nocache=0.7789015176240355:201
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/dispatch/Direct.js?nocache=0.9144717755261809:134
wrappedFunction  /qooxdoo/framework/source/class/qx/Interface.js?nocache=0.471329242689535:451
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/Manager.js?nocache=0.0028484577778726816:873
qx.Class.define.statics.fireNonBubblingEvent  /qooxdoo/framework/source/class/qx/event/Registration.js?nocache=0.22639847197569907:343
qx.Class.define.members.fireDataEvent  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:516
hideCallback  /unify/framework/source/class/unify/ui/core/PopOverManager.js?nocache=0.6557122371159494:200
callback  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:378
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/dispatch/Direct.js?nocache=0.9144717755261809:134
wrappedFunction  /qooxdoo/framework/source/class/qx/Interface.js?nocache=0.471329242689535:451
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/Manager.js?nocache=0.0028484577778726816:873
qx.Class.define.statics.fireEvent  /qooxdoo/framework/source/class/qx/event/Registration.js?nocache=0.22639847197569907:310
(anonymous function)
qx.Class.define.members.hide  /unify/framework/source/class/unify/ui/core/Widget.js?nocache=0.3822900871746242:1008
qx.Class.define.members.base  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:136
cb  /unify/framework/source/class/unify/view/ViewManager.js?nocache=0.17008754145354033:440
callback  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:378
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/dispatch/Direct.js?nocache=0.9144717755261809:134
wrappedFunction  /qooxdoo/framework/source/class/qx/Interface.js?nocache=0.471329242689535:451
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/Manager.js?nocache=0.0028484577778726816:873
qx.Class.define.statics.fireEvent  /qooxdoo/framework/source/class/qx/event/Registration.js?nocache=0.22639847197569907:310
qx.Class.define.members.fireEvent  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:465
animation  /unify/framework/source/class/unify/fx/MWidgetAnimation.js?nocache=0.532201623544097:103
callback  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:378
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/dispatch/Direct.js?nocache=0.9144717755261809:134
wrappedFunction  /qooxdoo/framework/source/class/qx/Interface.js?nocache=0.471329242689535:451
qx.Class.define.members.dispatchEvent  /qooxdoo/framework/source/class/qx/event/Manager.js?nocache=0.0028484577778726816:873
qx.Class.define.statics.fireNonBubblingEvent  /qooxdoo/framework/source/class/qx/event/Registration.js?nocache=0.22639847197569907:343
qx.Class.define.members.fireDataEvent  /qooxdoo/framework/source/class/qx/core/Object.js?nocache=0.9819487733766437:516
qx.Class.define.members.__finish  /unify/framework/source/class/unify/fx/core/Base.js?nocache=0.14104442414827645:173
step  /unify/framework/source/class/unify/fx/core/Animation.js?nocache=0.8293159897439182:137

**Comment by fastner** [comment]
It's fixed in commit 6269e2a976e898266d7a733f432a3441ac4dcf86
